<?php
namespace App\Controller\Api;


use Cake\Network\Exception\BadRequestException;
use Cake\ORM\TableRegistry;

/**
 * News Controller
 *
 */
class NewsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//       $bible = TableRegistry::get('bible');
//        var_dump($bible);die();
        return $this->jsonResponse('news controller');
    }

    public function add(){

        $data = $this->request->data;
        var_dump($data);
//        if($data['image']['size']> 9000000){
//           echo 'too more';
//        }else{
//            echo 'not more';
//        }

//        $uploaddir = 'uploads/';
//        $uploadfile = $uploaddir . basename($_FILES['image']['name']);
//        if (move_uploaded_file($_FILES['image']['tmp_name'], $uploadfile)) {
//            echo "Файл корректен и был успешно загружен.\n";
//        } else {
//            echo "Возможная атака с помощью файловой загрузки!\n";
//        }

//        var_dump($data['image']);
        die();
    }

    public function posta(){
        if($this->request->is('post')){
            $data = $this->request->data;
            return $this->jsonResponse($data);
        }
    }

    public function delete(){
        if($this->request->is('delete')){
            return $this->jsonResponse('deleted');
        }
        return $this->jsonResponse('not delete method');
    }

    public function edit(){
        if($this->request->is(['put', 'patch'])){
            return $this->jsonResponse('put or path');
        }
        return $this->jsonResponse('another http method');
    }

}
